spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: accounts
  profiles:
    active: production

# ACTUATOR INFO
info:
  app:
    name: "Accounts"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client: ${eureka-client}

application:
  allow-get-accounts: ${accounts.allow-get-accounts}